name: Secret Workflow

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the SECRET
        env:
          SECRET: ${{ secrets.SECRET }}  # Access the secret securely
        run: |
          echo "The secret has been accessed successfully."
          # Example: Use the secret to authenticate to a third-party API
          # curl -H "Authorization: Bearer $SECRET" https://api.example.com
