name: Secret Workflow

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Access Secret
        run: |
          echo "Using a secret, but keeping it safe!"
          echo "::add-mask::${{ secrets.SECRET }}"  # This hides the secret from logs

